import React from 'react'
import Head from 'next/head'

import styles from '../styles/general.module.css'

const about = () => {
  return (
    <div className={styles.container}>
       <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className={styles.bigText}>About Page</h1>
    </div>
  )
}

export default about